model:
  dataset_path: "/home/kit/iti/ew0464/gan_experiment/dataset/cifar-10-python.tar.gz" #dummy dataset.
  entry_point: "main.py" # The python file name that includes the function for evaluating the suggestions
  function_name: "run_hyperopt"
  copy_data: true # If the data should be copied in the workspace
git_options:
  git_uri: "git@github.com:u-adrian/Tutorial.git"
  branch: "main" # Either branch or version can be used. Using the option version allows to load specific tags
experiment:
  use_local_workspace: false # If a local experiment folder should be created in root folder or a dedicated workspace
                            # directory (https://wiki.bwhpc.de/e/Workspace)
  experiment_name: "tutorial_project"
  cluster: "horeka"  # Either "bwunicluster" or "horeka"
  number_chain_jobs: 4 # How many times should a job - the suggestion evaluation - be chained together. It is used to
                       # cirumvent the problem of time outs in the cluster
  multimetric_experiment: false
parameters:
  - name: max_depth
    type: int
    bounds:
      min: 1
      max: 10
  - name: n_estimators
    type: int
    bounds:
      min: 1
      max: 10
  - name: bootstrap
    type: int
    grid:
      - 0
      - 1
  - name: max_features
    type: categorical
    categorical_values:
      - 'sqrt'
      - 'log2'
  - name: criterion
    type: categorical
    categorical_values:
      - 'gini'
      - 'entropy'
metrics:
  - name: accuracy
    objective: maximize
    strategy: optimize
sbatch_options:
  partition: "dev_gpu_4"
  gres: "gpu:4"
  ntasks: 4
  mem-per-gpu: 32000
  time: "10"
sigopt_options:
  dev_run: false # If the dev api of sigopt should be used to get the suggestions
  project_id: "test_project"
  client_id: 11949
  observation_budget: 60 # Max number of trials
  parallel_bandwidth: 4 # Number of parallel evaluations
